README.md
Fixed bunch of typos, bad grammar etc..
=> Fixed title casing issues, typos and improved language

examples/hexagonal/index.css, examples/hexagonal/index.html, examples/hexagonal/js/entities/entities.js, examples/hexagonal/js/game.js, examples/hexagonal/js/resources.js, examples/hexagonal/js/screens/play.js, src/level/TMXConstants.js, src/level/TMXLayer.js, src/level/TMXMapReader.js, src/level/TMXRenderer.js
I started using melonjs because I saw Tiled had support for hex maps. Sat down to start my game and realized melonjs didn't! Well, now hopefully it will.
Implemented the tmx hexagonal rendering using the math from Tiled's same
renderer. Added an example which displays a hexagonal map and a tile's
index when moused over to show pixel to tile math.
Let me know if I'm missing anything, this is my first real open source pull request.
=> Implemented me.TMXHexagonalRenderer

src/level/TMXRenderer.js
Double checked all hex renderer methods are implemented.
=> Fix tiled object rendering position in hex

src/renderable/sprite.js
This appears to resolve the issue from my side. Tested rotation and scaling with a TexturePacker animation.
=> Fix for TexturePacker/ShoeBox rotate property

examples/particles/js/editor/controls.js, src/particles/emitter.js
Turns out my issue with #730, I was trying to set pos.z and it was expecting plain-old z. This fixes that, also the ParticleEmitter handles adding and removing its particle container instead of relying on the user to do so.
=> ParticleEmitter Z sorting and container

.jshintrc, src/vendors/tween.js
good with the life cycle methods
=> adds a proper init method to reset the vars, and ensure everything is

src/physics/quadtree.js
Here are the changes for quadTree usage with floating items as discussed in this topic:
https://groups.google.com/forum/#!topic/melonjs/osvb7I2a9C8
=> Use world coordinates for floating items.

src/video/video.js
As disussed in https://groups.google.com/d/topic/melonjs/sG8sGm5-E8o/discussion
=> Fix for getting parent node dimensions

src/video/video.js
=> Revert "Fix for getting parent node dimensions"

src/loader/loader.js
=> Made loader reentrant

src/video/video.js
=> Option to use getBoundingClientRect() for parent dimensions

src/renderable/sprite.js
I couldn't find a page in the wiki about standards for contributions. Hope this works for you. If not, let me know.
=> Fixes #884 by correcting @extends tag

src/renderable/sprite.js, tests/spec/sprite-spec.js
=> fix onComplete of setCurrentAnimation not called

examples/particles/js/entities/entities.js, examples/whack-a-mole/js/entities/entities.js, src/particles/emitter.js, src/particles/particle.js
=> Use me.Math.* instead of depricated/removed Number.prototype.*

src/level/TMXLayer.js
I need this because I use different tile size for different tile layer in Melon Editor
=> Different tile size for different tile layer

src/font/bitmaptext.js
Add anchorPoint property in super settings
=> set bitmap text anchor point in super

src/physics/body.js, src/system/timer.js
Functionality of the functions was unclear.  Updated documentation to more accurately describe their function
=> Updated comments of setInterval and setTimeout

src/renderable/colorlayer.js
I was expected that if you added this object to a container that the container would resize the render.  It does not.  It fills the whole viewport with the color
=> Updated Documentation

src/renderable/renderable.js
You may want to review my comment for accuracy
=> Updated comments to the scale method

dist/melonjs.js, dist/melonjs.module.d.ts, dist/melonjs.module.js, src/geometries/ellipse.js, src/geometries/line.js, src/geometries/path2d.js, src/geometries/poly.js, src/geometries/rectangle.js, src/geometries/roundrect.js, src/renderable/GUI.js, src/renderable/container.js, src/renderable/imagelayer.js, src/renderable/renderable.js, src/renderable/sprite.js, src/video/canvas/canvas_renderer.js, src/video/renderer.js, src/video/webgl/webgl_renderer.js
=> Replace @memberof T.prototype with @memberof T

webdoc.conf.json
=> Add og: meta tags for website previews

package-lock.json, package.json
https://github.com/webdoc-labs/webdoc/releases/tag/v2.0.0-beta
webdoc has changed to The Public Propsperity License, hence the major semver upgrade, as we talked about in our chat.
=> Upgrade to webdoc 2.0.0-beta

.github/ISSUE_TEMPLATE/bug_report.md
By commenting out the suggestions we can make sure people don't accidentally submit default information. Also I thought we could just combine the device info and the mobile info into one field to reduce redundancy.
=> Improve the Bug Report

src/state/state.js
When trying to understand transitions, the documentation for addTransition() was ambiguous as to whether the transition applied when leaving FROM the given state, or going TO the given state.  Updated documentation to clarify (after looking at code).
=> Improve documentation for addTransition().

dist/melonjs.mjs/utils/utils.js, dist/melonjs.module.js, src/utils/utils.js
Fix typo in parameter descriptions.
=> fix typo of document for checkVersion()

src/state/state.js
Fix the commented @name of state.DEFAULT
=> Fix doc comment in state.js

package-lock.json, package.json, src/loader/parsers/binary.js
Updated preload binary function so that it will now use fetch().
Added an import, as suggested: 'whatwg-fetch' -- a polyfill
=> updated XMLHttpRequest to fetch

package-lock.json, src/loader/parsers/tmx.js
Updated tmx.js to use the new fetchData function instead of XML/XHR.
Reference issue: 1176
NOTE: I updated a bunch of package-lock.json stuff on my end while trying to troubleshoot an error I was having that was un-related, somehow it made it into the pull request. If needed, reject this pull request and just copy/paste the tmx.js file. If maintainer sees this: Obiot is aware of the error I am talking about.
=> Update to tmx.js - see NOTE
