melonjs/melonJS

src/level/TMXRenderer.js

Corrected staggering logic for flat top hexagons. Will add a flat-top example later to show that the rendering works fine for both types of rotation but wanted to get this bug fix in ASAP.

Fix for flat-top hexagonal rendering bug

---

examples/particles/js/editor/controls.js
examples/particles/js/editor/widgets.js
plugins/debug/debugPanel.js
src/lang/error.js
src/lang/object.js
src/lang/window.js
src/level/TMXMapReader.js
src/level/TMXObjectGroup.js
src/level/TMXRenderer.js
src/level/TMXTileset.js
src/math/matrix2.js
src/math/vector2.js
src/math/vector3.js
src/plugin/plugin.js
src/shapes/ellipse.js
src/shapes/poly.js
src/state/state.js
src/utils/color.js
src/video/canvas/texture.js
src/video/renderer.js
src/video/texture_cache.js
src/video/webgl/compositor.js
tests/spec/inheritance-spec.js
tests/spec/plugin-spec.js

Issue: Object.extend in melonJS conflicts with the Facebook SDK causing the SDK to not load properly. melonJS games that try to use the Facebook SDK with melonJS are not able to do so.
Fixes #699. Related to #666. Changes include...
- attached extend property to me.Object rather than Object (i.e. me.Object.extend)
- attached me.Object.extend to Error.extend
- changed all instances of Object.extend to me.Object.extend
Also...
- I updated this jsFiddle with the new changes as well: http://jsfiddle.net/jdrorrer/7z3t2o4s/
- all tests are passing
The issue can be recreated by forking and building a game built on melonJS that uses the Facebook SDK. A good example of this is Clumsy Bird: https://github.com/ellisonleao/clumsy-bird. It has a Facebook share button when the game ends.
Side note …

Patched Object.extend simple inheritance to fix conflict with Facebook SDK

---

src/renderable/sprite.js

If you attempt to create a Sprite object by specifying a string corresponding to a preloaded resource, such as:
`this.bg = new me.Sprite(0, 0, {image: "intro_bg"});`
with the current code, you'll get the error `Uncaught me.Vector2d.Error: invalid x,y parameters (not a number)` because you're referring to the `image` passed in as an argument (which is a string, not an object) and thus without any `width` or `height` properties.  These are added by a call a few lines before this:
`this.image = me.utils.getImage(image);`

Fix for Sprite objects initialized with a string argument for "image".

---

src/input/pointer.js

Just adding the 4th element of the POINTER_DOWN array to the check for bound pointer events.

[#872] Add touchstart to pointer event check

---

scripts/travis-upload.sh

- The nodeJS version was updated in `.travis.yml`, but not updated here

Fix artifact uploads on travis

---

src/renderable/renderable.js

I would like suggest a different way to flip renderable, because the current flip function doesn't work well with me.sprite since it flips relative to the x or y axis of the world. This flip function is mainly done in the predraw function and will take into account the current position and anchor point of the renderable so that the flipped sprite stays in its place

flip relative to the middle axis of a renderable

---

src/renderable/container.js
src/renderable/renderable.js
src/renderable/sprite.js

When a renderable is floating, the location of the image and the bound is different (the image is floating but the bound still follow its container). I found problem like gui_object become unclickable because of this. However I'm not sure if this can affect other function

Floating renderable's bounds still follows its container position

---

src/level/TMXObject.js
src/level/TMXTiledMap.js

The object position for isometric map in melon editor and in melonJS is already the same, unlike in tiled, so there is no need to adjust position. 
For now, I use data.tiledversion in the map object to check if a map is from tiled

Remove adjust position for non-tiled map

---

src/config.js

There is no "document.location" for Wechat mini game platform.

Fixed for Wechat mini game platform.

---

src/level/tiled/TMXTileMap.js

If you have a text node in your map and you have a collision layer, Melon will try to add a collisionType to the node (which has an undefined body)
and crash:
```
Uncaught TypeError: Cannot set property 'collisionType' of undefined
at Class.getObjects (melonjs.js:29365)
at Class.addTo (melonjs.js:29253)
at loadTMXLevel (melonjs.js:26961)
at safeLoadLevel (melonjs.js:26918)
at Object.api.loadLevel (melonjs.js:27098)
at PlayScreen.onResetEvent (play.ts:47)
at PlayScreen.reset (melonjs.js:13423)
at Object._switchState (melonjs.js:13585)
```
A text node looks like this:
```
{
"isRenderable": true,
"isKinematic": true,
"currentTransform": {
"val": {
"0": 1,
"1": 0,
"2": 0,
"3": 0,
"4": 1,
"5": 0,
"6": 0,
"7": 0,
"8": 1
},
"className": "me.Matrix2d"
},
"alwaysUpdate": false,
"updateWhenPaused": …
```

Fix trying to add collisionType to text nodes

---

src/level/tiled/TMXTileset.js

Hi !
Using Tiled Version 1.7.2.
I don't really know when the format changed, but here is my fix.
I tested it and it works consistantly in my project for both TMX and JSON formats.
Do not hesitate to edit the code if necessary as I am not familliar with Javascript.
PS. Loving MelonJS!

Fixed tile properties import for new Tiled JSON format

---

src/input/pointerevent.js

Dear Olivier, I believe this fixes the bug. I have checked releasePointerEvent and it does not refer to "this" at all. Cheers, Wilson.

Changed this.releasePointerEvent to releasePointerEvent as it was causing a "this is undefined" error.

---

README.md
package-lock.json

Moved the tutorial instructions directly below "Using melonJS", bolded the sentence "For your first time using melonJS, use either of these tutorials for setting up the engine. These are where you start".  Made "basic hello world example" bold.

Edited README for clarity

---

package.json

By overriding publish command (using "prepublish") instead of using the release script we can prevent accidentally doing the publish command without testing (as it's now enforced) and the command is more conventional

improve the build scripts to prevent accidental publishes without testing

---

package.json

I made a mistake. The "prepublish" script runs before publish and install, but "prepublishOnly" only works on publish

fix a bug with the new script making install fail

---

src/entity/entity.js
src/geometries/poly.js
src/input/gamepad.js
src/lang/deprecated.js
src/math/vector2.js
src/math/vector3.js
src/physics/body.js
src/renderable/imagelayer.js
src/state/state.js
src/system/device.js
src/text/text.js
src/tweens/easing.js
src/tweens/interpolation.js
src/tweens/tween.js
src/video/webgl/utils/uniforms.js

* Use @member instead of @type so webdoc knows we're documenting a class member.
* Change `/**` to `/*` where it's not an actual _documentation_ comment.
* Fix the "device" namespace so the namespace is the actual object and remove all @memberof tags pointing to that 
namespace in the object properties (webdoc parses the object properties automatically!)≈

Fix all DocParser errors in webdoc

---

src/loader/parsers/image.js
src/loader/parsers/json.js
src/loader/parsers/tmx.js

Userstory: I have several levels with separate manifests. This manifests contains some part of the same assets. If I load second level after complete first, I don't want to load asset I previously loaded.

prevent load previously loaded resource

---

src/loader/loader.js
src/system/event.js

Userstory: I am trying to load project, but due to problems with the internet connection some of my assets load fails. I don't want to reload page and load whole project again. I want to upload again only failed assets.
Example decision: add notification about load failure with button to upload this asset again using `rePreload` function

feat: handle assets load error

---

docker/Dockerfile
docker/generate-docs.sh
package.json

Documentation build helper via a docker container to work around broken webdoc package's absolute-path html anchor generation. See issue #1216.
Run `cd docker && ./generate-docs.sh` to generate the webdoc `docs` with correct line-number references in html.
Irrelevant, this is an infrastructure change that doesn't affect any source code.

added build helper docker to generate webdoc with correct relative paths

---

src/loader/parsers/tmx.js

Dear Olivier,
I would like to suggest this change as for those of us using a build step (React / Vue), "tsx" is usually recognised as a typescript-jsx file type which renders us unable to import an asset with that extension as it would be parsed wrongly. Therefore, I suggest to use the type attribute instead of the file extension if available. Also, if the type is XML, it should allow the user to deal with whatever was parsed rather than simply returning nothing.

Use tmxData.type instead of file extension and also return a result for xml extension

---

.github/workflows/test.yml
.vscode/extensions.json
.vscode/settings.json
eslint.config.mjs
package-lock.json
package.json
rollup.config.mjs
scripts/dist.js
scripts/pretest.js

- Fixed so that Windows users can run the test suite.  
- Added a GH workflow that runs the tests in both node 20(lts) and node 22 and in both ubuntu and windows environment.
- Pinned version of package manager to the npm version of the npm version provided in the latest node lts version to ensure better reliability during installation of dependencies.

Fix running of tests on windows machine
